import crypto from "crypto";
import { SPOTIFY_ENCRYPTION_SECRET } from "../config/env/env.spotify.js";

// `aes-256-gcm` is an authenticated encryption algorithm that provides both confidentiality and integrity.
const key = crypto.createHash("sha256").update(SPOTIFY_ENCRYPTION_SECRET).digest();

// Encrypts a string using AES-256-GCM and returns a base64-encoded string containing the IV, authentication tag, and ciphertext.
export function encrypt(value: string) {
    const iv = crypto.randomBytes(12); // initialisation vector
    const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);

    // Encrypt the value and concatenate the IV, authentication tag, and ciphertext into a single Buffer, then encode it as base64 for storage.
    const encrypted = Buffer.concat([
        cipher.update(value, "utf-8"),
        cipher.final()
    ]);
    // Get the authentication tag generated by the cipher, which is essential for verifying the integrity of the ciphertext during decryption.
    const tag = cipher.getAuthTag()
    // The final output is a base64 string that combines the IV, authentication tag, and encrypted data. This format allows the decryption function to easily extract the necessary components for decryption and integrity verification.
    return Buffer.concat([iv, tag, encrypted]).toString("base64");
}

// Decrypts a base64-encoded string that contains the IV, authentication tag, and ciphertext, and returns the original plaintext string. It verifies the integrity of the data using the authentication tag before decryption.
export function decrypt(value: string) {
    // Decode the base64 string back into a Buffer, then extract the IV, authentication tag, and encrypted data based on their known lengths (IV is 12 bytes, tag is 16 bytes).
    const buffer = Buffer.from(value, "base64");

    // The IV is the first 12 bytes, the authentication tag is the next 16 bytes, and the remaining bytes are the encrypted data.
    const iv = buffer.subarray(0, 12); // initialisation vector
    const tag = buffer.subarray(12, 28); // authentication tag
    const encrypted = buffer.subarray(28); // encrypted data

    // Create a decipher instance using the same algorithm, key, and IV. Set the authentication tag to ensure that the integrity of the data is verified during decryption. 
    // If the authentication tag does not match (indicating that the data has been tampered with or the wrong key/IV is used), the decryption will fail and throw an error.
    const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv); // create decipher instance
    decipher.setAuthTag(tag); // set authentication tag for integrity verification

    // Decrypt the data by processing the encrypted Buffer through the decipher. The result is a Buffer containing the original plaintext, which is then converted back to a UTF-8 string before being returned.
    return Buffer.concat([
        decipher.update(encrypted),
        decipher.final(),
    ]).toString("utf8");
}

/* 
The IV ensures that encrypting identical plaintexts twice yields different ciphertexts — this protects against replay analysis and pattern leaks.
The IV does not need to be secret, but it must be unpredictable for security.

takes multiple Buffers and joins them into one continuous Buffer 
Here it joins 
The ciphertext segments from update 
The final bytes from final 
This is a common Node pattern when encrypting in chunks.

AES-GCM is a stream mode, not a block-padding mode.

Think of AES-GCM decryption as:
“Decrypt only if this data is provably authentic.”

ES-GCM decryption reconstructs the IV, verifies the authentication tag, and only then releases the plaintext — guaranteeing both secrecy and integrity.

When using authenticated encryption (like GCM), the cipher computes an authentication tag.
This tag proves:
The ciphertext was not modified
The correct key was used
The IV was the one initially used
Without a valid tag, decryption should fail.
In Node.js, .getAuthTag() returns a Buffer containing that tag. You must pass it during decryption. 
*/